### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by icode** [alexisvincent/systemjs-hmr#19]
```
TypeError: Object.values is not a function
    at Object.getDependencies (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:10909:63)
    at Object.hasDependency (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:10914:20)
    at eval (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:10922:22)
    at Array.filter (native)
    at Object.getDependents (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:10921:27)
    at findDependants (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11079:38)
    at eval (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11143:16)
From previous event:
    at SystemJSLoader$1.System.reload (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.6/dist/systemjs-hmr.js:11140:28)
    at fileChanged (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:8615:12)
    at Socket.eval (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:8643:58)
    at Socket.Emitter.emit (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:4138:20)
    at Socket.onevent (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:7212:10)
    at Socket.onpacket (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:7170:12)
    at Manager.eval (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:6939:15)
    at Manager.Emitter.emit (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:4138:20)
    at Manager.ondecoded (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:7778:8)
    at Decoder.eval (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:6939:15)
    at Decoder.Emitter.emit (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:2193:20)
    at Decoder.add (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:2635:12)
    at Manager.ondata (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:7768:16)
    at Socket$1.eval (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:6939:15)
    at Socket$1.Emitter.emit (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:4138:20)
    at Socket$1.onPacket (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:6578:14)
    at WS.eval (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:6395:10)
    at WS.Emitter.emit (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:4138:20)
    at WS.Transport$1.onPacket (http://localhost:9080/jspm_packages/npm/systemjs-hot-reloader@1.1.0/dist/index.js:4315:8)
```

chrome  52.0.2743.116 (64-bit)

**Comment by alexisvincent** [comment]
Thanks, assumed Babel would polyfill this. Will fix.

**Comment by icode** [comment]
@alexisvincent I'm just use systemjs+plugin-babel (jspm) on browser, not run nodejs

**Comment by alexisvincent** [comment]
Pushed a new version. Can you check if this solves your issue?

**Comment by icode** [comment]
thanks fix
