### ISSUE TITLE
parentKey.indexOf is not a function

### ISSUE THREAD

**Issue by icode** [alexisvincent/systemjs-hmr#20]
```
systemjs-hmr.js:12432 Error: parentKey.indexOf is not a function
  Resolving http://localhost:9080/src/dev/css-parser.js to 1
    at getParentMetadata (http://localhost:9080/jspm_packages/system.src.js:1563:42)
    at SystemJSLoader$1.normalize (http://localhost:9080/jspm_packages/system.src.js:1580:24)
    at http://localhost:9080/jspm_packages/system.src.js:318:27
From previous event:
    at eval (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.7/dist/systemjs-hmr.js:12422:12)
From previous event:
    at eval (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.7/dist/systemjs-hmr.js:12417:10)(anonymous function) @ systemjs-hmr.js:12432tryCatcher @ systemjs-hmr.js:6747Promise._settlePromiseFromHandler @ systemjs-hmr.js:4892Promise._settlePromise @ systemjs-hmr.js:4949Promise._settlePromise0 @ systemjs-hmr.js:4994Promise._settlePromises @ systemjs-hmr.js:5069(anonymous function) @ systemjs-hmr.js:2033
```

**Comment by callmetango** [comment]
Same here using `systemjs@0.20.9` and `systemjs-hmr@2.0.7`.

Quick workaround: Change lines 12420:12422 of `node_modules/systemjs-hmr/dist/systemjs-hmr.js` from
~~~ JavaScript
return bluebird.resolve(entries)
// resolve all entries
.map(resolve)
~~~
to
~~~ JavaScript
return bluebird.resolve(entries)
// resolve all entries
.map(function (entry) {
  return resolve(entry);
})
~~~
Sorry, could not investigate further.

**Comment by alexisvincent** [comment]
Will push a fix this evening

**Comment by alexisvincent** [comment]
Fixed in 2.0.8

**Comment by alexisvincent** [comment]
@callmetango Thanks, used your fix. Don't understand why it fixes it, but hey :)

**Comment by callmetango** [comment]
Me neither. :-) But anyway: Your welcome!
