### ISSUE TITLE
TypeError: Cannot read property '__reload' of undefined

### ISSUE THREAD

**Issue by icode** [alexisvincent/systemjs-hmr#21]
```
TypeError: Cannot read property '__reload' of undefined
    at eval (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.7/dist/systemjs-hmr.js:12401:104)
From previous event:
    at eval (http://localhost:9080/jspm_packages/npm/systemjs-hmr@2.0.7/dist/systemjs-hmr.js:12388:25)
```

**Comment by alexisvincent** [comment]
Fixed in 2.0.8
